### ISSUE TITLE
Error writing cfg files

### ISSUE THREAD

**Issue by AxelTerizaki** [thebezelproject/BezelProject-Windows#3]
Hello.

I had installed version 1.0 when this project was announced and it works great, thank you.

I wanted to update to 1.5 but I'm running into a problem with the installer.

It downloads the first pack, but then says it can't write config files and asks to abort, retry or ignore. 

![bezel_project_web_installer_v1 5_2019-06-15_18-14-47](https://user-images.githubusercontent.com/4531597/59553743-bc187b00-8f99-11e9-9d1d-35a32306ef21.png)

I tried to run it from the retroarch folder. Same problem happens between windows 7 or 10.

How can I fix this? Thanks in advance.

**Comment by nunovic** [comment]
Have you figured out a solution? Same is happening to me. Only version it didn't happen was with version 1 installation, that worked just fine.

**Comment by AxelTerizaki** [comment]
I sadly haven't :( Sorry.

**Comment by Griffen8280** [comment]
It would appear that the issue stems from trying to install the bezel packages and cfg files into the wrong location.  The default app install location is typically in C:\Program Files(x86)\RetroArch however in the newer versions of RetroArch they install to C:\Users\%UserName%\AppData\Roaming\RetroArch.  Since the 1.4 version of the installer here the user cannot change/specify this folder as the default install location.  This basically gives you 2 options until they fix this (maybe in 1.6?)
1. Re-Install RetroArch and specify that you want it installed in Program Files instead of the default location.
2. Use the 1.3 version of the Bezel Project installer file which still allows you to specify the RetroArch installation location.

I will continue to fool around with this and see if I can maybe force it to install in the proper location from the command line.

**Comment by AxelTerizaki** [comment]
Thanks for looking into the issue. :)

**Comment by Griffen8280** [comment]
Update:
No go on forcing the installer to write to a new location.  If this installer was an msi type then there are command line options that can be used to force installation to a different location.  However not in the case of this specific exe type installer (1.4 & 1.5 versions).  Currently the only ways to get this installed is by using the methods from my previous post.

Hopefully when the installer for version 1.6 is created it will include the option to select an install folder otherwise that will have to be done using the RetroArch installer for the foresee-able future of new versions for this project.

**Comment by robertvb83** [comment]
This is exactly the same for me. I played around with this and i actually found a workaround!

@AxelTerizaki @Griffen8280 Just use the wizzard for each system one by one. So uncheck everything and then just check one system. It will then ask for the installation path of RA

**Comment by AxelTerizaki** [comment]
Interesting bug, thanks @robertvb83 The problem is I have too many systems, this is going to take a long while, haha :p

**Comment by thebezelproject** [comment]
Sorry for the delay in seeing this.

This version of the Windows installer isn't being worked on/updated by the original developer and will be archived off very soon. I have written a different Windows based installer that will be posted up to take its place. Please check back soon.
